blank_issues_enabled: true
contact_links:
  - name: Ask a question ❓
    url: https://github.com/ormikopo1988/NetCoreAngularApp.Template/discussions/new
    about: Ask a question or request support for using the template